<?php

namespace Modules\Authentication\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Authentication\Models\Character;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $charachters = [
            'Visionary Leader' => ['image' => 'The Visionary Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Strategic Leader. You excel in problem-solving and have strong leadership skills. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with strategy and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'high', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Excels in problem-solving and leadership. Needs improvement in self-management and tech skills.'],
            'Strategic Leader' => ['image' => 'The Strategic Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Self-Reliant Leader. You excel in problem-solving and self-management, making you a reliable and self-sufficient leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with confidence and self-reliance, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'medium', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Strong in problem-solving with medium leadership. Needs improvement in self-management and tech skills.'],
            'Self-Reliant Leader' => ['image' => 'The Self-Reliant Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Balanced Leader. You excel in problem-solving and have balanced self-management skills. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with balance and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'low', 'self_magment' => 'high', 'ai_and_tech' => 'low'], 'desc' => 'Excels in problem-solving and self-management. Needs improvement in leadership and tech skills.'],
            'Balanced Leader' => ['image' => 'The Balanced Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Tech-Savvy Leader. You excel in problem-solving and technology, making you a forward-thinking and innovative leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with tech-savviness and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'low', 'self_magment' => 'medium', 'ai_and_tech' => 'low'], 'desc' => 'Strong in problem-solving with medium self-management. Needs improvement in leadership and tech skills.'],
            'Tech-Savvy Leader' => ['image' => 'The Tech-Savvy Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Innovative Leader. You excel in problem-solving and have a strong grasp of technology. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with innovation and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'high'], 'desc' => 'Excels in problem-solving and AI & technology. Needs improvement in leadership and self-management.'],
            'Innovative Leader' => ['image' => 'The Innovative Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Inspiring Leader. You excel in leadership and inspire those around you. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with inspiration and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'medium'], 'desc' => 'Strong in problem-solving with medium AI & technology. Needs improvement in leadership and self-management.'],
            'Inspiring Leader' => ['image' => 'The Inspiring Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Practical Leader. You excel in leadership and problem-solving, making you a practical and effective leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with practicality and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'high', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Strong in leadership with medium problem-solving. Needs improvement in self-management and tech skills.'],
            'Inspiring Leader' => ['image' => 'The Inspiring Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Tech Leader. You excel in leadership and self-management, making you a balanced and effective leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with balance and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'high', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Strong in leadership with medium problem-solving. Needs improvement in self-management and tech skills.'],
            'Practical Leader' => ['image' => 'The Practical Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Analytical Leader. You excel in leadership and have a balanced approach to self-management. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with analysis and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'medium', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Balanced in leadership and problem-solving. Needs improvement in self-management and tech skills.'],
            'Tech Leader' => ['image' => 'The Tech Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Comprehensive Leader. You excel in leadership and technology, making you a comprehensive and forward-thinking leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with comprehensive skills and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'low', 'self_magment' => 'medium', 'ai_and_tech' => 'low'], 'desc' => 'Balanced in leadership with high self-management. Needs improvement in problem-solving and tech skills.'],
            'Analytical Leader' => ['image' => 'The Analytical Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Balanced Strategist. You excel in leadership and have a balanced approach to technology. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with strategy and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'low', 'self_magment' => 'medium', 'ai_and_tech' => 'low'], 'desc' => 'Balanced in leadership with medium self-management. Needs improvement in problem-solving and tech skills.'],
            'Comprehensive Leader' => ['image' => 'The Comprehensive Leader.svg', 'statements' => 'To embark on your development journey, your character style is The Visionary Self-Manager. You excel in self-management and leadership, making you a visionary and reliable leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with vision and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'high'], 'desc' => 'Balanced in leadership with high AI & technology. Needs improvement in problem-solving and self-management.'],
            'Balanced Strategist' => ['image' => 'The Balanced Strategist.svg', 'statements' => 'To embark on your development journey, your character style is The Practical Self-Manager. You excel in self-management and leadership, making you a practical and reliable leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with practicality and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'medium'], 'desc' => 'Balanced in leadership with medium AI & technology. Needs improvement in problem-solving and self-management.'],
            'Visionary Self-Manager' => ['image' => 'The Visionary Self-Manager.svg', 'statements' => 'To embark on your development journey, your character style is The Comprehensive Self-Manager. You excel in self-management, making you a reliable and comprehensive leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with comprehensive skills and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'high', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Strong in self-management with medium leadership. Needs improvement in problem-solving and tech skills.'],
            'Practical Self-Manager' => ['image' => 'The Practical Self-Manager.svg', 'statements' => 'To embark on your development journey, your character style is The Balanced Self-Manager. You excel in self-management and problem-solving, making you a balanced and reliable leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with balance and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'medium', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Balanced in self-management and leadership. Needs improvement in problem-solving and tech skills.'],
            'Comprehensive Self-Manager' => ['image' => 'The Comprehensive Self-Manager.svg', 'statements' => 'To embark on your development journey, your character style is The Visionary Technologist. You excel in technology, making you a forward-thinking and visionary leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with tech-savviness and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'low', 'self_magment' => 'high', 'ai_and_tech' => 'low'], 'desc' => 'Excels in self-management. Needs improvement in leadership and problem-solving.'],
            'Balanced Self-Manager' => ['image' => 'The Balanced Self-Manager.svg', 'statements' => 'To embark on your development journey, your character style is The Analytical Technologist. You excel in technology, making you a balanced and analytical leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with tech-savviness and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'low', 'self_magment' => 'medium', 'ai_and_tech' => 'low'], 'desc' => 'Balanced in self-management and problem-solving. Needs improvement in leadership and tech skills.'],
            'Visionary Technologist' => ['image' => 'The Visionary Technologist.svg', 'statements' => 'To embark on your development journey, your character style is The Balanced Individual. You excel in multiple areas, making you a well-rounded and balanced leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with balance and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'high'], 'desc' => 'Excels in AI & technology. Needs improvement in leadership and problem-solving.'],
            'Analytical Technologist' => ['image' => 'The Analytical Technologist.svg', 'statements' => 'To embark on your development journey, your character style is The Generalist. You have room to grow in multiple areas, making this an exciting opportunity for comprehensive development. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you enhance your abilities across all areas. Begin your adventure with determination, taking meaningful steps toward a well-rounded future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'medium'], 'desc' => 'Balanced in AI & technology. Needs improvement in leadership and problem-solving.'],
            'Balanced Individual' => ['image' => '', 'statements' => 'To embark on your development journey, your character style is The Empathetic Strategist. You excel in problem-solving and leadership, making you a dynamic and influential leader. Your unique blend of skills positions you as a strategic thinker with a strong ability to connect and inspire those around you.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'medium', 'self_magment' => 'medium', 'ai_and_tech' => 'medium'], 'desc' => 'Balanced in all areas.'],
            'Generalist' => ['image' => '', 'statements' => 'We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with empathy, strategy, and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'low', 'leadership' => 'low', 'self_magment' => 'low', 'ai_and_tech' => 'low'], 'desc' => 'Needs improvement in all areas.'],
            'Empathetic Strategist' => ['image' => '', 'statements' => 'To embark on your development journey, your character style is The Visionary Innovator. You excel in problem-solving, leadership, and technology, making you a dynamic and influential leader. Your unique blend of skills positions you as a forward-thinking and innovative force capable of driving significant change and inspiring those around you.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'high', 'self_magment' => 'medium', 'ai_and_tech' => 'low'], 'desc' => 'The Empathetic Strategist is a well-rounded leader excelling in problem-solving and people skills. This character style is marked by a strong ability to connect with and inspire others, making them effective in leadership roles. While their self-management skills are developing, they possess the ability to maintain a balanced approach to their tasks and responsibilities. Despite a lower proficiency in AI and technology, the Empathetic Strategist uses their strategic thinking and interpersonal skills to navigate challenges and drive success through collaborative and human-centric approaches.'],
            'Visionary Innovator' => ['image' => '', 'statements' => 'We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with vision, innovation, and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'high', 'self_magment' => 'low', 'ai_and_tech' => 'high'], 'desc' => 'The Visionary Innovator thrives at the intersection of problem-solving, leadership, and technology. This character style embodies a blend of strategic thinking and forward-looking insight, making them capable of envisioning and driving transformative changes. With a strong aptitude for AI and technology, the Visionary Innovator not only solves complex problems but also leads teams with charisma and inspiration. Despite a current low in self-management skills, this individual has the potential to balance these traits, harnessing their tech-savvy nature and leadership prowess to excel in dynamic environments.'],
            'Harmonious Strategist' => ['image' => '', 'statements' => 'To embark on your development journey, your character style is The Harmonious Strategist. You excel in leadership, people skills, and self-management, making you a dynamic and reliable leader. Your unique blend of skills positions you as a strategic thinker capable of inspiring and guiding those around you.', 'scores' =>  ['problem_solving' => 'medium', 'leadership' => 'high', 'self_magment' => 'high', 'ai_and_tech' => 'medium'], 'desc' => 'The Harmonious Strategist is a well-rounded individual who excels in leadership and people skills while maintaining a high level of self-management. This character style is marked by a strong ability to connect with and inspire others, making them highly effective in leadership roles. With a medium proficiency in problem-solving and technology, the Harmonious Strategist uses a strategic and collaborative approach to overcome challenges and drive success. Their ability to manage tasks efficiently and maintain balance in their professional and personal life is a key strength'],
            'Innovative Problem Solver' => ['image' => '', 'statements' => 'To embark on your development journey, your character style is The Innovative Problem Solver. You excel in problem-solving and self-management, making you an innovative and effective leader. We have crafted a personalized roadmap to guide you in achieving your short-term and long-term goals. Tailored to your unique character style, this roadmap will help you further enhance your abilities. Begin your adventure with innovation and determination, taking meaningful steps toward a brilliant future. Your success is our mission.', 'scores' =>  ['problem_solving' => 'high', 'leadership' => 'medium', 'self_magment' => 'high', 'ai_and_tech' => 'high'], 'desc' => 'Excels in problem-solving and self-management with medium leadership. Needs improvement in tech skills.'],
        ];

        foreach ($charachters as $title => $charachter) {
            Character::updateOrCreate(
                ['title' => $title],
                [
                    "ai_and_tech" => $charachter['scores']['ai_and_tech'],
                    "self_managment" => $charachter['scores']['self_magment'],
                    "problem_solving" => $charachter['scores']['problem_solving'],
                    "leader_ship_and_pepple_skills" => $charachter['scores']['leadership'],
                    'desc' => $charachter['desc'],
                    'statment' => $charachter['statements'],
                    'image' => $charachter['image'],
                ]
            );
        }
    }
}
