services:

  # nginx:
  #   build:
  #     context: "./docker/services/nginx"
  #     dockerfile: Dockerfile
  #   container_name: road_map_nginx
  #   ports:
  #    - 80:80
  #   volumes:
  #    - ${API_PWD}:/var/www/html 
  #   networks:
  #     - road_map_network
  #   depends_on:
  #     - php

  php:
    build: 
      context: "./docker/services/php"
      dockerfile: Dockerfile
    container_name: road_map_php
    volumes:
     - ${API_PWD}:/var/www/html
    networks:
      - road_map_network
    depends_on:
      - mysql

  mysql:
    image: ${DB_IMAGE}
    container_name: road_map_mysql
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - ${SERVICES_PWD}/mysql/volume_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - road_map_network

networks:
  road_map_network:
    driver: bridge